### ISSUE TITLE
`pkgdown` site for `ggpval`?

### ISSUE THREAD

**Issue by dbrookeUAB** [s6juncheng/ggpval#12]
I quickly made a `pkgdown` website for `ggpval`, and I think it'll help increase its visibility. [Here is a preview.](https://dbrookeuab.github.io/ggpval/)

I can help you set up a custom url and to setup `travis_ci()` if you're interested.

**Comment by s6juncheng** [comment]
Wow amazing!! Thanks! Yes that would be very helpful!

**Comment by dbrookeUAB** [comment]
Awesome!! I'm not sure this is the best way, but maybe you could create a branch called website and I could submit a pull-request from my website branch?

Then you just have to go to `Settings` and scroll down to `github-pages`.  Set branch to `website` and folder as `\docs`.

**Comment by s6juncheng** [comment]
Great! I have now created a `website` branch. https://github.com/s6juncheng/ggpval/tree/website. Please just let me know what else I can do.

**Comment by dbrookeUAB** [comment]
Let's start simply with github-pages and do the following
> Then you just have to go to `Settings` and scroll down to `github-pages`. Set branch to `website` and folder as `\docs`.

It'll take awhile for the site to render but there will be a link for that site. Copy the link and open the settings from the about section on the main page. You'll see a box titled website for you to paste the link. I could do this for you quickly, but I need more permissions. That being said, we're learning here! 😋

**Comment by s6juncheng** [comment]
Hi @dbrookeUAB I just did it as you described, it looks amazing! Thanks a lot, I'm really learning:)

**Comment by dbrookeUAB** [comment]
Looks great!
