### ISSUE TITLE
t.test parameters

### ISSUE THREAD

**Issue by alienzj** [s6juncheng/ggpval#2]
Hello!
for example:
``` r
plane_p <- add_pval(plane_p, pairs = list(c(1, 2)), test = "t.test")
```
How should I specify the parameters used by t.test？
I want to specify 
``` r
t.test(..., alternative = "less")
```
Thanks very much!

**Comment by s6juncheng** [comment]
Hi,
thanks for raising out the issue,  indeed this was missing from the previous version, I added this feature. Please install the new version from github.  
`devtools::install_github("s6juncheng/ggpval")` 
`plane_p <- add_pval(plane_p, pairs = list(c(1, 2)), test = "t.test",  alternative = "less")`
