### ISSUE TITLE
use correct annotation when faceting 

### ISSUE THREAD

**Issue by c-mertes** [s6juncheng/ggpval#9]
currently when using a facet with annotation it only uses the first one from the list.

```
add_pval(plt, pairs = list(c(1, 2)), annotation = list("Awesome1", "Awesome2"))
```
results in this figure:

![image](https://user-images.githubusercontent.com/22544249/92077564-89f76280-ed71-11ea-83f4-dbea790e6cd6.png)

Where `Awesome2` is missing.

**Comment by s6juncheng** [comment]
Thanks Chris, looks great!
